apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopify-sync-state
  labels:
    app.kubernetes.io/name: shopify-sync
    app.kubernetes.io/component: state
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
